-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: flake8
-   repo: https://github.com/adarnimrod/shell-pre-commit
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: &shellscripts collectd/collectd_facts|nginx/nginx_facts|ssl/dhparams
    -   id: shellcheck
        files: *shellscripts
-   repo: https://github.com/adarnimrod/ansible-pre-commit.git
    sha: v0.6.0
    hooks:
    -   id: ansible-syntax-check
        files: &playbook tests/playbook.yaml
-   repo: https://github.com/willthames/ansible-lint
    sha: v3.4.13
    hooks:
    -   id: ansible-lint
        files: *playbook
