---
language: python
python: "2.7"
dist: trusty
sudo: false
services: [docker]
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

env:
  - DOCKER=ubuntu:trusty
  - DOCKER=ubuntu:xenial
  - DOCKER=debian:jessie

install:
  - pip install pre_commit ansible | cat

before_script:
  - docker run --detach --name $(echo $DOCKER | sed 's/:/_/g') $DOCKER tail -f /.dockerenv

script:
  - pre-commit run --all-files
  - ansible-playbook -i $(echo $DOCKER | sed 's/:/_/g'), -c docker -vv playbook.yml
