---
- hosts: all
  gather_facts: False
  tasks:
  - name: Update APT sources
    raw: DEBIAN_FRONTEND=noninteractive apt-get update
    changed_when: False

  - name: APT install Python
    raw: DEBIAN_FRONTEND=noninteractive apt-get install -qy python2.7 python
    register: debian_bootstrap_install_python
    changed_when: "'Unpacking' in debian_bootstrap_install_python.stdout"

  - name: Gather facts
    setup:

  - name: APT install
    apt:
      name: ['nginx-light', 'collectd-core', 'openssl']
      state: present
      install_recommends: no

  - name: Collectd facts
    collectd_facts:
    register: collectd_facts

  - name: Debug
    debug:
      var: collectd_facts
      verbosity: 2

  - name: Assertions
    assert:
      that:
      - collectd_facts|changed == False
      - collectd.major is number
      - collectd.minor is number
      - collectd.patch is number

  - name: Nginx facts
    nginx_facts:
    register: nginx_facts

  - name: Debug
    debug:
      var: nginx_facts
      verbosity: 2

  - name: Assertions
    assert:
      that:
      - nginx_facts|changed == False
      - nginx.major is number
      - nginx.minor is number
      - nginx.patch is number
      - nginx.version is defined

  - name: DH params for missing file
    ignore_errors: True
    dhparams:
      path: /etc/ssl/dhparams.pem
    register: missing_dhparams

  - name: Debug
    debug:
      var: missing_dhparams
      verbosity: 2

  - name: Assertions
    assert:
      that:
      - missing_dhparams.bits == 0
      - missing_dhparams|failed == True
      - missing_dhparams|changed == False

  - name: Generate DH params
    command: openssl dhparam -out /etc/ssl/dhparams.pem 2048
    changed_when: True

  - name: DH params for existing file
    dhparams:
      path: /etc/ssl/dhparams.pem
    register: existing_dhparams

  - name: Debug
    debug:
      var: existing_dhparams
      verbosity: 2

  - name: Assertions
    assert:
      that:
      - existing_dhparams.bits == 2048
      - existing_dhparams|failed == False
      - existing_dhparams|changed == False
      - existing_dhparams.path == '/etc/ssl/dhparams.pem'
