#!/bin/sh -e
. "$1"

fail ()
{
    echo "{\"failed\": true, \"msg\": \"$1\"}"
    exit
}

which collectd || fail "Can't find collectd executable."

collectd -h | sed -n 's/[a-zA-Z ]*\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/{"changed": false, "ansible_facts": {"collected": {"major":\1, "minor":\2, "patch":\3}}}/p'
