#!/bin/sh -e
# shellcheck disable=SC1090
. "$1"

fail ()
{
    echo "{\"failed\": true, \"msg\": \"$1\"}"
    exit
}

command -v collectd > /dev/null 2>&1 || fail "Can't find collectd executable."

collectd -h 2>&1 | sed -n 's/[a-zA-Z ]*\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/{"changed": false, "ansible_facts": {"collectd": {"major":\1, "minor":\2, "patch":\3, "version":"\1.\2.\3"}}}/p'
